### ISSUE TITLE
Don't write DATE-OBS, MJD-OBS

### ISSUE THREAD

**Issue by PaulPrice** [Starlink/ast#7]
We've discovered that AST is writing an incorrect `DATE-OBS` and `MJD-OBS` to our FITS headers (we haven't told the `FrameSet` the epoch, so it's coming out as ~2000-01-01). The epoch of observation can be vague (e.g., coadds), and in any case we're tracking it using other mechanisms so we don't want AST clobbering our values or writing incorrect values.

Can we add an attribute to AST to disable writing of `DATE-OBS` and `MJD-OBS`? I'm happy to do the work if this is approved.

**Comment by PaulPrice** [comment]
(Or can we check if the value is `AST__BAD` before writing it?)

**Comment by dsberry** [comment]
My only concern with this (and your other issue about zero-valued CDi_j values) is to do with proliferation of attributes. There are a myriad of ways in which users could potentially want to tweak the FITS headers produced by the FitsChan class. To have a separate attribute for each such tweak could very easily become unwieldy. However, that's  not to say we can't have a few such attributes, but I'd like to make sure first that there is no other convenient way to achieve the same effect. For DATE-OBS/MJD-OBS I see two other possible options:

1 - since you say you know from other sources what the right value should be, why not just assign this right value to the Epoch attribute of the FrameSet before writing it out to the FitsChan?

2 - another option is to write the unaltered FrameSet to the FitsChan, and then change the value of the resulting DATE-OBS/MJD-OBS keywords  in the FitsChan before finally transferring the FitsChan contents to the FITS file. Or you could instead just delete the offending keywords from the FitsChan.  By default the contents of the FitsChan are transferred to the external file when the FitsChan is deleted, but you can force an early  transfer by calling astWriteFits.

This second option could also be used to handle your issue relating to zero-valued CDi_j keywords. That is, after the FrameSet has been written to the FitsChan, check to see if all CDi_j keywords are present, and add any (with value zero) that are missing.

Do either of these two options sound practical to you?

**Comment by PaulPrice** [comment]
We had thought of those solutions, but weren't sure of what to implement, so I thought I would start at AST first since that's where the FITS headers originate. I think adding these tweaks to AST would be the cleanest solution (it seems to me that it's always better to produce the desired answer from the start than to produce something close to the desired answer and then modify it), but there are certainly other solutions.

In modifying the headers produced by AST, I feel better about adding keywords that don't exist (`CDi_j`) than deleting keywords (`DATE-OBS`, `MJD-OBS`), so I think I will try adding the check for `AST__BAD` (that doesn't increase "proliferation of attributes") to see if that works.

**Comment by dsberry** [comment]
Let me know if you are unsure about how to implement things with AST.  Several other projects handle these sorts of issues by post processing the headers produced by AST to their own specific requirements. Regarding the use of AST__BAD, setting the Epoch attribute of a Frame to AST__BAD has the same effect as clearing the attribute. So the DATE-OBS value will still end up set to the default value. It would be better to use some finite value impossibly far in the future or past in place of AST__BAD.

**Comment by PaulPrice** [comment]
After a bit of poking around, I'm thinking post-processing might be the way to go...

Just out of curiosity, do you know why the `MJD-OBS` is coming out as 51544.4992571308 instead of 51544.5?

**Comment by dsberry** [comment]
OK. My memory is not what it used to be. Having actually looked at the code, I now see that clearing the Epoch attribute before writing the FrameSet to the FitsChan should result in no DATE-OBS or MJD-OBS keywords being generated. I suspect the default value of J2000.0 must have been set explicit at some point in your code. So you may find that doing "astClear( fs, "Epoch" );"  (where "fs" is your FrameSet pointer) immediately before calling astWrite fixes the DATE-OBS issue.

The change from 51544.5 to 51544.4992571308 is caused by the different timescale requirements for the Epoch attribute in AST and the DATE-OBS FITS keyword - AST requires the Epoch value to be in the TDB timescale but FITS requires DATE-OBS to be in UTC. So AST converts Epoch from TDB to UTC before writing it out to DATE-OBS.

**Comment by PaulPrice** [comment]
Ah, that's very helpful! I discovered that the WCS going into AST contains `EQUINOX = 2000` (with the code comment "not needed, but may help some older code"). Removing that, the `DATE-OBS` and `MJD-OBS` are gone. Clearly AST is doing the right thing.

Thanks for your help!
